### ISSUE TITLE
the import gives me errors

### ISSUE THREAD

**Issue by mawij2023** [OrderFlowTools/InitialBalance#1]
Hi, I really appreciate your work and your willingness to share it. Thanks so much.

I am trying to import the indicator but it keeps giving me errors. Do you know if it should show up if I don't have a lifetime license?

I have tried importing the whole zip, inner folders, the indicator itself...

One of the errors  (importing .cs) is below (it says unhandled exception: End of Central Directory record could not be found)
![image](https://user-images.githubusercontent.com/125421369/218908889-f0b3b1a6-f65e-488d-b3ba-f120e9cea526.png)

When I try the folder, it says its made for an older ninja or it is not compatible.

Thanks for your help!

**Comment by gemgit7** [comment]
Thanks for reporting this @mawij2023. I've updated the releases with an updated add-on archive.  The NT ecosystem will be updated soon. In the meantime, please use the updated version from the release page (https://github.com/OrderFlowTools/InitialBalance/releases) to install into NT8.
