### ISSUE TITLE
Initial balance not showing?

### ISSUE THREAD

**Issue by davidoff999** [OrderFlowTools/InitialBalance#2]
the previous one are showing but not today market open.
![2023-09-05_175216](https://github.com/OrderFlowTools/InitialBalance/assets/141419253/95269178-2389-4b23-bc7d-bc798a3b7c64)

**Comment by tradrdude** [comment]
That’s due to holiday hours from Labor Day (USA). It’ll be cleared and acting normal tomorrow.

**Comment by gemgit7** [comment]
You know @tradrdude and @davidoff999 I noticed that too. I do believe @tradrdude is right in that it has to do with the holiday hours, but I'm curious as to why it behaved like that.

**Comment by gemgit7** [comment]
@davidoff999, would you mind trying the latest (v1.3) version?

**Comment by davidoff999** [comment]
yes, thank you
