### ISSUE TITLE
Opening range not showing

### ISSUE THREAD

**Issue by gerald560** [OrderFlowTools/InitialBalance#3]
Text is there but lines are not

![image](https://github.com/OrderFlowTools/InitialBalance/assets/12697408/012caf19-317b-47c9-8176-3358315de003)

**Comment by gemgit7** [comment]
@gerald560 it looks like you may be using the 'Minimal' mode, which only display current IB and extensions as markers on the margin. If you need the full display with the lines, try the Full mode in the 'Display Mode' dropdown. 
Hope that helps.
